### ISSUE TITLE
Load stack size limit fail

### ISSUE THREAD

**Issue by szdytom** [TimHsue/TJudger#3]
我在运行test/test.c时，提示Load stack size limit fail，然后每个文件都CE，请问是这么回事？

**Comment by TimHsue** [comment]
是setrlimit函数在设置栈大小限制时出现的问题，最有可能的原因：
1. 2 * 设置的栈空间大小超出系统空间大小
2. 预设的内存空间上限MEMTOP (1024 * 1024 * 1024)超出系统空间大小

如果排除以上问题，建议修改源码查看errno的值
EPERM：权限不足
EFAULT：参数地址无法访问
EINVAL：参数无效
然后再进一步分析
（今天才发现自己当时英语一塌糊涂....
顺祝新年快乐

**Comment by szdytom** [comment]
已经解决了，我最开始是在WSL上测试的。
现在装了一台真机ubuntu就没问题了。
